"""add-mask-artifact

Revision ID: c95c4ece6697
Revises: 9e9b507ce965
"""
from alembic import op
import sqlalchemy as sa


revision = 'c95c4ece6697'
down_revision = '9e9b507ce965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jewel_instances', sa.Column('mask_artifact', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jewel_instances', 'mask_artifact')
    # ### end Alembic commands ###

